/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cifrado.viggener;

import java.util.Locale;
import static javafx.scene.paint.Color.color;
import static javafx.scene.paint.Color.color;
import javax.swing.JOptionPane;

public class Ventana extends javax.swing.JFrame {


    Vigikawaii vigi= new Vigikawaii();
    
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_key = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_msj = new javax.swing.JTextArea();
        btn_des = new javax.swing.JButton();
        btn_cifra = new javax.swing.JButton();
        btn_clean = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txt_p = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 153));
        jLabel1.setText("Vigenere");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 510, 38));

        txt_key.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 11)); // NOI18N
        txt_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_keyActionPerformed(evt);
            }
        });
        getContentPane().add(txt_key, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 270, 20));

        txt_msj.setColumns(20);
        txt_msj.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 11)); // NOI18N
        txt_msj.setRows(5);
        jScrollPane1.setViewportView(txt_msj);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 290, 170));

        btn_des.setForeground(new java.awt.Color(0, 0, 0));
        btn_des.setText("DESCIFRAR");
        btn_des.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desActionPerformed(evt);
            }
        });
        getContentPane().add(btn_des, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 140, 40));

        btn_cifra.setForeground(new java.awt.Color(0, 0, 0));
        btn_cifra.setText("CIFRAR");
        btn_cifra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cifra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cifraActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cifra, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 130, 40));

        btn_clean.setForeground(new java.awt.Color(0, 0, 0));
        btn_clean.setText("BORRAR");
        btn_clean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cleanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clean, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 140, 40));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 102));
        jLabel4.setText("Respuesta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 102));
        jLabel7.setText("Texto");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 102));
        jLabel5.setText("CLAVE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 102));
        jLabel6.setText("CLAVE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 270, -1));

        txt_p.setBackground(new java.awt.Color(255, 51, 102));
        txt_p.setForeground(new java.awt.Color(0, 0, 204));
        txt_p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo1.jpg"))); // NOI18N
        getContentPane().add(txt_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desActionPerformed
        // TODO add your handling code here:
        if (txt_key.getText().length() < 1 || txt_msj.getText().length() < 1) {
            JOptionPane.showMessageDialog(null,"Incerta una clave y texto a cifrar");
        }else{
            if (txt_key.getText().length() > txt_msj.getText().length()) {
            
            JOptionPane.showMessageDialog(null,"La clave debe ser menor al tecto a Decifrar");
            
        }else{
            
            jTextField1.setText(vigi.desencriptarTextoCifrado(txt_msj.getText(), txt_key.getText().toUpperCase()));
 
        
        }
        }
        
        
        
    }//GEN-LAST:event_btn_desActionPerformed

    private void txt_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_keyActionPerformed

    private void btn_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cleanActionPerformed
        // TODO add your handling code here:
        txt_msj.setText(" ");
        txt_key.setText(" ");
    }//GEN-LAST:event_btn_cleanActionPerformed

    private void btn_cifraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cifraActionPerformed
        // TODO add your handling code here:

        if (txt_key.getText().length() < 1 || txt_msj.getText().length() < 1) {
            JOptionPane.showMessageDialog(null,"Es necesario agregar texto");
        }else{
            if (txt_key.getText().length() > txt_msj.getText().length()) {
            
            JOptionPane.showMessageDialog(null,"La clave debe ser de un tamaño menor del texto a cifrar");
            
        }else{
            /*txt_msj.getText().toUpperCase();
            txt_key.getText().toUpperCase();*/
            
            jTextField1.setText(vigi.encriptarTextoClaro(txt_msj.getText().toUpperCase(), txt_key.getText().toUpperCase()));
        
        }
        }

        
    }//GEN-LAST:event_btn_cifraActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cifra;
    private javax.swing.JButton btn_clean;
    private javax.swing.JButton btn_des;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_key;
    private javax.swing.JTextArea txt_msj;
    private javax.swing.JLabel txt_p;
    // End of variables declaration//GEN-END:variables
}
